<!--
*** Keep this commented as as it overrides some CSS settings for
*** <H3>, <H2>, ... tags.
**
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">
-->

<?php
        session_start();
      //Put session start at the beginning of the file
        //ini_set('session.cache_limiter', 'private');
        header("Expires: Sat, 01 Jan 2000 00:00:00 GMT");
        header("Last-Modified: ".gmdate("D, d M Y H:i:s")." GMT");
        header("Cache-Control: post-check=0, pre-check=0",false);
        //session_cache_limiter("must-revalidate");
	//
//	echo "In " . __FILE__ . ", Session Name: " . session_name();


?>


<?php
	/*include 'server.php'; /* format page bitmap coords */
	include 'php/parse_url.php'; /* format page bitmap coords */
?>
<HTML>
<HEAD>
<TITLE><?php include 'php/get_main_title.php' ?></TITLE>
<link rel="stylesheet" href=<?php include 'php/set_css.php' ?> >  
</HEAD>

<style>

</style>

<body>


<div id="sub_main_menu_wrapper">
<center><font size="3"  color="black" style="font-style:italic;background-color:yellow;"><?php include 'php/get_release_prop_msg.php' ?></font></center>
</div>

<H3 id="main_menu_title_large"><center><?php include 'php/get_main_title.php' ?></center></H3>
<H2 id="main_menu_title_medium"><center><?php include 'php/get_sub_title.php' ?></center></H2>
<H1 id="main_menu_title_small"><center><?php include 'php/get_sub_title1.php' ?><font size="1" color="<?php include 'php/get_release_color.php' ?>">(<?php include 'php/get_release_name.php' ?>)</font></center></H1>

<div id="main_menu_wrapper">

<form action="action_page.php" method="post"> 
<label for="release"><font size="4" color="<?php include 'php/get_main_prompt_color.php' ?>">
<?php include 'php/get_main_prompt.php' ?>
</font>
</label>

<!--label for="release">Choose a Release:</label-->

<select id="release" name="release" onclick="choose(this);" size="1">
	<?php include 'pulldown_menu1.php';?>
</select>

<?php include 'pulldown_menu2.php';?>


<br><br>
<input type="submit" value=<?php include 'php/get_submit_prompt.php' ?> >
</form>

</div>

<script type="text/javascript">
/*
* PLEASE READ THIS COMMENTS BLOCK TO BETTER UNDERSTAND WHAT THIS JAVASCRIP IS DOING
* AND BEFORE MAKING ANY CHANGES.
*
* ***** THIS SCRIPT IS GENERATED BY index.php 
*
* When a user clicks on the first menu option and selects a release this scrip will then dynamically 
* generate the second pulldown menu (tyle.display = 'inline') and will reset the second pulldown 
* menus fo all the other releases (style.display = 'none')
*
* if (relName == 'honolulu') {
                document.getElementById(relDoc).style.display = 'inline';
                document.getElementById('guilin-doc-type').style.display = 'none';
                document.getElementById('frankfurt-doc-type').style.display = 'none';
        }

*/

function choose(opt) {
	var i;
	var n;
        var relSelected = opt.selectedIndex;
        var selected_relName = opt.options[relSelected].value;
        var selected_relDoc;
        var not_selected_relDoc;
	/*
		*  Format the release array in real-time based on what is in 
		*  the oanp_releases.json. Any chages made to the onap_release.json
		*  will change the contents of this array and therefore the pulldown
		*  menus
	*/
	<?php include 'php/get_js_rel_array.php';?>
        
	selected_relDoc = selected_relName + "-doc-type";

	document.getElementById(selected_relDoc).style.display = 'inline';
	/*
		* name="doc_type" is the attribute, $_POST['doc_type'] that is the doc_type
		* attribute that is sent to action_page.php along with the 'release' 
		* attribute, $_POST['release']
	 */

	document.getElementById(selected_relDoc).name = "doc_type";

	for (i = 0; i < releases.length; i++) {
	/*
		*    VERY IMPORTANT - PLEASE READ
		* 
		* 
	 */
		
		/*
			* Find the release name
			* .. and do nothing if it is a match as name='doc_name' has already 
			* been set
		 */

		n = selected_relName.localeCompare(releases[i])

		if (n !== 0) {
		/*
			* .. For all other second pulldopwn menus for the rest of the releases
			* we have to set name ="" otherwise the browser will send 
			* all 'doc_type' attributes it finds on the page to actiion_page.php
			* via the $_POST['doc_type'] variable
		 */
			/*
				*
				* Format the "<select id= >" tag
				*
			 */
			not_selected_relDoc =  releases[i] + "-doc-type";
			/*
				*
				* set the display to 'none' so the menu for this release
				* does not display on the screen
				*
			 */
			document.getElementById(not_selected_relDoc).style.display = 'none';
			/*
				*
				* set the the "name" attribute to "" so that the browser
				* ignores this "select> block
				* does not display on the screen
				*
			 */
			document.getElementById(not_selected_relDoc).name = "";
		}

	}
}

</script>
</body>
</HTML>
