
<?php 
//
// $_POST = array(
//	'release'=>'guilin',
//	'doc_type'=>'dev-guide',
//);

#	'release'=>'Debug-is-on',

//$release_name = "honolulu";
//$doc_type = "use-cases";

//require_once "onapdocs_functions.php";

$release_name = $_SESSION["release"];
$doc_type = $_SESSION["doc_type"];

$css_tag = "position-main";
$static_usemap_id  = "image-map";


$dir_path= format_db_path();
$file_name = $dir_path . "/" . "global_config/topics.json";

//echo "In " . __FILE__ . ", line " . __LINE__ . ": " . $file_name;
$readjson = file_get_contents($file_name);

//Decode JSON
$data = json_decode($readjson, true);
//
// The follwoing code generates HTML comments to help in debugging
// viow the HTML source and look for this comment by the <img>  tag
//
//echo "<!-- " . "These comments are generated by a .php to help with debbuging  " .  
//" -->" . PHP_EOL;
//echo "<!-- " . "JSON File is: "
//	. $file_name .  
//" -->" . PHP_EOL;
//
// End og HTML comments generation
//
//prt_debug_as_comments ($file_name, __FILE__, __LINE__);

foreach ($data as $rel) {

//echo "Release value: " . $rel['release_value'] . PHP_EOL;

	if ($rel['release_value'] == $release_name) {
		//
		// If image_uri at the document level (doc_type) is set use it; otherwise default yp the
		// release level image_uri
		//
		$json_image_uri = $rel['image_uri'];

		$options_count = sizeof ($rel["options"]);

		for ( $i = 0; $i < $options_count; $i++)
		{
			if (strcmp($rel["options"][$i]["value"], $doc_type ) == 0) {
				 
				if ( !empty($rel["options"][$i]["image_uri"]) ) {
					//
					//image_uri at the doc_type level is set; use it
					//
					$json_image_uri = $rel["options"][$i]['image_uri'];

				}
			}
		}

		//
		// if the json_image_uri is not a link then create the relative path name to the
		// image file in coomon/images/"path_uri"
		//
		if ( filter_var ($json_image_uri, FILTER_VALIDATE_URL) === FALSE ) {
			 $image_uri = set_img_uri ($json_image_uri);
		} else {
			$image_uri = $json_image_uri;
		}

		echo "<img  id = " . "\"". $css_tag ."\"\n";
		echo "\tsrc = ";
		echo "\"" . $image_uri . "\"\n";
		echo "\talt = \"Image file  >>>[" . $image_uri . "] not found]\"\n";
		echo "\tusemap = "."\""."#".$static_usemap_id."\""."\n";
		//
		echo ">\n";
		//echo "\t<map name = "."\"".$doc_type."\"".">\n";
		//
	}


}
?> 
